-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 16:28:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipos_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `descripcion_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usu` INT NOT NULL AUTO_INCREMENT,
  `usuario_usu` VARCHAR(45) NOT NULL,
  `rol_usu` INT NOT NULL,
  `nombre_usu` VARCHAR(45) NULL,
  `apellidos_usu` VARCHAR(45) NULL,
  `fechanac_usu` DATE NULL,
  `telefono_usu` VARCHAR(45) NULL,
  `correo_usu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usu`, `rol_usu`),
  CONSTRAINT `fk_usuarios_tipos_roles1`
    FOREIGN KEY (`rol_usu`)
    REFERENCES `mydb`.`tipos_roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`contrasenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrasenas` (
  `idusuario_contra` INT NOT NULL,
  `contrasena_contra` VARCHAR(45) NOT NULL,
  `fecha_contra` DATE NOT NULL,
  PRIMARY KEY (`idusuario_contra`),
  CONSTRAINT `fk_contrasenas_usuarios1`
    FOREIGN KEY (`idusuario_contra`)
    REFERENCES `mydb`.`usuarios` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos_restricciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_restricciones` (
  `id_restriccion` INT NOT NULL AUTO_INCREMENT,
  `descripcion_restriccion` VARCHAR(45) NULL,
  `edad_restriccion` INT NULL,
  PRIMARY KEY (`id_restriccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peliculas` (
  `id_peli` INT NOT NULL AUTO_INCREMENT,
  `nombre_peli` VARCHAR(100) NOT NULL,
  `nombre_director_peli` VARCHAR(100) NOT NULL,
  `fecha_peli` YEAR NOT NULL,
  `restriccion_peli` INT NOT NULL,
  `categoria1_peli` INT NOT NULL,
  `caratula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_peli`),
  CONSTRAINT `fk_peliculas_tipos_restricciones1`
    FOREIGN KEY (`restriccion_peli`)
    REFERENCES `mydb`.`tipos_restricciones` (`id_restriccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peliculas_tipos_categorias1`
    FOREIGN KEY (`categoria1_peli`)
    REFERENCES `mydb`.`tipos_categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salas` (
  `id_sala` INT NOT NULL AUTO_INCREMENT,
  `nombre_sala` VARCHAR(45) NULL,
  `capacidad_sala` INT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesiones` (
  `id_sesion` INT NOT NULL AUTO_INCREMENT,
  `peliculas_id_peli` INT NOT NULL,
  `fecha_sesion` DATE NOT NULL,
  `hora_sesion` TIME(1) NOT NULL,
  `sala_sesion` INT NOT NULL,
  `sesionescol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sesion`),
  CONSTRAINT `fk_sesiones_peliculas1`
    FOREIGN KEY (`peliculas_id_peli`)
    REFERENCES `mydb`.`peliculas` (`id_peli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_salas1`
    FOREIGN KEY (`sala_sesion`)
    REFERENCES `mydb`.`salas` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asientos` (
  `sesion_asiento` INT NOT NULL,
  `fila_asiento` INT NOT NULL,
  `n_asiento` INT NOT NULL,
  PRIMARY KEY (`fila_asiento`, `n_asiento`, `sesion_asiento`),
  CONSTRAINT `fk_asientos_sesiones1`
    FOREIGN KEY (`sesion_asiento`)
    REFERENCES `mydb`.`sesiones` (`id_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tickets` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `usuario_ticket` INT NOT NULL,
  `fecha_ticket` DATE NULL,
  `hora_ticket` TIME(1) NULL,
  `sesion_ticket` INT NOT NULL,
  `fila_asiento_ticket` INT NOT NULL,
  `num_asiento_ticket` INT NOT NULL,
  PRIMARY KEY (`id_ticket`),
  CONSTRAINT `fk_tickets_usuarios`
    FOREIGN KEY (`usuario_ticket`)
    REFERENCES `mydb`.`usuarios` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_asientos1`
    FOREIGN KEY (`fila_asiento_ticket` , `num_asiento_ticket` , `sesion_ticket`)
    REFERENCES `mydb`.`asientos` (`fila_asiento` , `n_asiento` , `sesion_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valoraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`valoraciones` (
  `idusuario_val` INT NOT NULL,
  `pelicula_val` INT NOT NULL,
  `valoracion_val` INT NOT NULL,
  PRIMARY KEY (`idusuario_val`, `pelicula_val`),
  CONSTRAINT `fk_usuarios_has_peliculas_usuarios1`
    FOREIGN KEY (`idusuario_val`)
    REFERENCES `mydb`.`usuarios` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_peliculas_peliculas1`
    FOREIGN KEY (`pelicula_val`)
    REFERENCES `mydb`.`peliculas` (`id_peli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
