-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 18:44:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usu` INT NOT NULL AUTO_INCREMENT,
  `nombre_usu` VARCHAR(45) NULL,
  `apellido1_usu` VARCHAR(45) NULL,
  `apellido2_usu` VARCHAR(45) NULL,
  `fechanac_usu` DATE NULL,
  `telefono_usu` VARCHAR(45) NULL,
  `correo_usu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrasenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrasenas` (
  `usuarios_id_usu` INT NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `fecha_contra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuarios_id_usu`),
  CONSTRAINT `fk_contrasenas_usuarios1`
    FOREIGN KEY (`usuarios_id_usu`)
    REFERENCES `mydb`.`usuarios` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos_restricciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_restricciones` (
  `id_restriccion` INT NOT NULL,
  `descripcion_restriccion` VARCHAR(45) NULL,
  `edad_restriccion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_restriccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_categorias` (
  `id_categoria` INT NOT NULL,
  `descripcion_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peliculas` (
  `id_peli` INT NOT NULL,
  `nombre_peli` VARCHAR(45) NOT NULL,
  `nombre_director_peli` VARCHAR(45) NOT NULL,
  `fecha_peli` YEAR NOT NULL,
  `restriccion_peli` INT NOT NULL,
  `categoria1_peli` INT NOT NULL,
  PRIMARY KEY (`id_peli`),
  CONSTRAINT `fk_peliculas_tipos_restricciones1`
    FOREIGN KEY (`restriccion_peli`)
    REFERENCES `mydb`.`tipos_restricciones` (`id_restriccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peliculas_tipos_categorias1`
    FOREIGN KEY (`categoria1_peli`)
    REFERENCES `mydb`.`tipos_categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarjetas` (
  `usuarios_id_usu` INT NOT NULL,
  `ntarjeta_tarjeta` VARCHAR(45) NOT NULL,
  `cvv_tarjeta` VARCHAR(45) NOT NULL,
  `fechacad_tarjeta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuarios_id_usu`, `ntarjeta_tarjeta`),
  CONSTRAINT `fk_tarjetas_usuarios1`
    FOREIGN KEY (`usuarios_id_usu`)
    REFERENCES `mydb`.`usuarios` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salas` (
  `id_sala` INT NOT NULL,
  `nombre_sala` VARCHAR(45) NULL,
  `capacidad_sala` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesiones` (
  `id_sesion` INT NOT NULL,
  `peliculas_id_peli` INT NOT NULL,
  `fecha_sesion` VARCHAR(45) NULL,
  `hora_sesion` VARCHAR(45) NULL,
  `sala_sesion` INT NOT NULL,
  PRIMARY KEY (`id_sesion`),
  CONSTRAINT `fk_sesiones_peliculas1`
    FOREIGN KEY (`peliculas_id_peli`)
    REFERENCES `mydb`.`peliculas` (`id_peli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_salas1`
    FOREIGN KEY (`sala_sesion`)
    REFERENCES `mydb`.`salas` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asientos` (
  `sesion_asiento` INT NOT NULL,
  `fila_asiento` INT NOT NULL,
  `n_asiento` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fila_asiento`, `n_asiento`, `sesion_asiento`),
  CONSTRAINT `fk_asientos_sesiones1`
    FOREIGN KEY (`sesion_asiento`)
    REFERENCES `mydb`.`sesiones` (`id_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tickets` (
  `id_ticket` INT NOT NULL,
  `usuario_ticket` INT NOT NULL,
  `fecha_ticket` VARCHAR(45) NULL,
  `sesion_ticket` INT NOT NULL,
  `fila_asiento_ticket` INT NOT NULL,
  `num_asiento_ticket` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_ticket`),
  CONSTRAINT `fk_tickets_usuarios`
    FOREIGN KEY (`usuario_ticket`)
    REFERENCES `mydb`.`usuarios` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_asientos1`
    FOREIGN KEY (`fila_asiento_ticket` , `num_asiento_ticket` , `sesion_ticket`)
    REFERENCES `mydb`.`asientos` (`fila_asiento` , `n_asiento` , `sesion_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
